In [99]:
import pandas as pd 

df = pd.read_csv('../../wikidata_global_companies_info.csv') 
df.head(2)

,Unnamed: 0,wikidata_uri,company name,description,country,instance of,inception,official website,industry,founded by
0,0,http://www.wikidata.org/entity/Q279260,Hotel Sacher,"building in Innere Stadt, Vienna, Austria",Austria,['hotel' 'Viennese coffee house'],1876-01-01,http://www.sacher.com/,['hotel'],Édouard Sacher
1,1,http://www.wikidata.org/entity/Q193326,Goldman Sachs,American investment bank,United States of America,['stock exchange' 'bank' 'multinational corpor...,1869-01-01,https://www.goldmansachs.com/,['financial services' 'financial sector'\n 'fi...,Samuel Sachs

In [100]:
df2 = pd.read_csv('../../classification-dataset-v1.csv') 
df2.head(2)

,Category,website,company_name,homepage_text,h1,h2,h3,nav_link_text,meta_keywords,meta_description
0,Commercial Services & Supplies,bipelectric.com,bip dipietro electric inc,Electrici...,NaN,NaN,NaN,NaN,"electricians vero beach, vero beach electrical...","Providing quality, reliable full service resid..."
1,Healthcare,eliasmedical.com,elias medical,site map | en español Elias Medical h...,Offering Bakersfield family medical care from ...,Welcome to ELIAS MEDICAL#sep#Family Medical Pr...,Get To Know Elias Medical#sep#Family Medical P...,NaN,Elias Medical bakersfield ca family doctor med...,For the best value in Bakersfield skin care tr...

In [101]:
df2 = df2.rename(columns = {'company_name': 'company name' , 'meta_description' : 'description' , 'Category': 'industry' })

In [102]:
df = df[['company name' , 'description' , 'industry']] 
df2 = df2[['company name' , 'description' , 'industry']]

In [103]:
data = pd.concat([df, df2]) 
data.head()

,company name,description,industry
0,Hotel Sacher,"building in Innere Stadt, Vienna, Austria",['hotel']
1,Goldman Sachs,American investment bank,['financial services' 'financial sector'\n 'fi...
2,Sberbank,Russian banking and financial services company,['banking in Russia' 'financial sector'\n 'fin...
3,Heineken,Dutch beer company,['beverage industry']
4,Deutsche Bank,German global banking and financial services c...,['financial services' 'Other monetary intermed...

In [104]:
print(data.iloc[0, 2])
print(type(data.iloc[0, 2]))

['hotel']
<class 'str'>

In [105]:
data.shape

(77553, 3)

In [106]:
original = pd.read_csv('ExioNAICS.csv') 
original = original[['NAICS_2 Title' , 'NAICS_2 Code']] 

SECTOR_MERGE = {
    '31': '31-33', '32': '31-33', '33': '31-33',
    '44': '44-45', '45': '44-45',
    '48': '48-49', '49': '48-49',
} 
original['NAICS_2 Code'] = original['NAICS_2 Code'].astype(str)
original['NAICS_2 Code'] = original['NAICS_2 Code'].map(SECTOR_MERGE).fillna(original['NAICS_2 Code'])

In [107]:
title_code_matching = {}

titles = original['NAICS_2 Title' ].to_list() 
codes = original['NAICS_2 Code'].to_list()

for i in range(len(titles)):
    if titles[i] not in title_code_matching:
        title_code_matching[titles[i]] = codes[i] 

title_code_matching

{'Retail Trade': '44-45',
 'Information': '51',
 'Manufacturing': '31-33',
 'Finance and Insurance': '52',
 'Mining, Quarrying, and Oil and Gas Extraction': '21',
 'Other Services (except Public Administration)': '81',
 'Wholesale Trade': '42',
 'Public Administration': '92',
 'Agriculture, Forestry, Fishing and Hunting': '11',
 'Transportation and Warehousing': '48-49',
 'Real Estate and Rental and Leasing': '53',
 'Professional, Scientific, and Technical Services': '54',
 'Construction': '23',
 'Arts, Entertainment, and Recreation': '71',
 'Health Care and Social Assistance': '62',
 'Administrative and Support and Waste Management and Remediation Services': '56',
 'Accommodation and Food Services': '72',
 'Utilities': '22',
 'Educational Services': '61',
 'Management of Companies and Enterprises': '55'}

In [ ]:
for v,k in title_code_matching.items():
    if len(v.split(" ")) > 1:
        words = v.split(" ") 
        words = a.str.replace(r"[\[\]'\"\n]" , "" , regex = True) for a in words

In [ ]:
data['industry'] = data['industry'].str.replace(r"[\[\]'\"\n]" , '' , regex = True)
data['industry']  = data['industry'].str.replace(r"," , "" , regex = False )
data['industry']  = data['industry'].str.split(" ")

['hotel']
['financial', 'services', 'financial', 'sector', 'financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding']
['banking', 'in', 'Russia', 'financial', 'sector', 'financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding']
['beverage', 'industry']
['financial', 'services', 'Other', 'monetary', 'intermediation', 'financial', 'sector', 'financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding']
['food', 'industry', 'beverage', 'industry']
['brewing']
['tertiary', 'sector', 'of', 'the', 'economy']
['food', 'industry']
['financial', 'services', 'insurance', 'financial', 'sector', 'economics', 'of', 'banking']
['telecommunications', 'mobile', 'phone', 'industry']
['financial', 'services', 'financial', 'sector', 'economics', 'of', 'banking']
['brewing']
['financial', 'services', 'financial', 'sector']
['financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding', 'financial', 'services']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['financial', 'services', 'financial', 'sector', 'economics', 'of', 'banking']
['financial', 'services', 'International', 'Standard', 'Industrial', 'Classification', 'financial', 'sector', 'bank']
['financial', 'services', 'financial', 'sector', 'financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding', 'economics', 'of', 'banking']
['brewing']
['financial', 'sector']
['financial', 'services']
['beverage', 'industry']
['Internet']
['telecommunications']
['Internet', 'industry']
['brewing']
['brewing']
['food', 'and', 'tobacco', 'industry', 'Manufacture', 'of', 'beer', 'brewing']
['brewing']
['brewing']
['brewing']
['telecommunications']
['telecommunication']
['telecommunications']
['telecommunications', 'All', 'Other', 'Telecommunications', 'Other', 'Computer', 'Related', 'Services', 'Wired', 'Telecommunications', 'Carriers', '2007–present', 'definition']
['internet', 'service', 'provider']
['telecommunication']
['internet', 'service', 'provider']
['telecommunication']
['financial', 'services', 'financial', 'sector', 'economics', 'of', 'banking']
['telecommunication', 'telecommunications']
['telecommunications']
['television', 'mass', 'media', 'film', 'industry']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['financial', 'services', 'financial', 'sector', 'economics', 'of', 'banking']
['financial', 'sector', 'financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding', 'financial', 'services', 'economics', 'of', 'banking']
['financial', 'services', 'economics', 'of', 'banking']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['financial', 'services', 'economics', 'of', 'banking']
['financial', 'sector', 'financial', 'services']
['financial', 'services']
['financial', 'services', 'financial', 'sector', 'economics', 'of', 'banking']
['financial', 'sector']
['financial', 'services', 'financial', 'sector', 'economics', 'of', 'banking']
['financial', 'services', 'economics', 'of', 'banking']
['financial', 'sector']
['brewing']
['financial', 'services', 'financial', 'sector', 'economics', 'of', 'banking']
['bank']
['financial', 'services', 'financial', 'sector', 'financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding']
['financial', 'sector', 'financial', 'services', 'financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding', 'economics', 'of', 'banking']
['financial', 'sector']
['financial', 'services', 'financial', 'sector', 'economics', 'of', 'banking']
['financial', 'services']
['financial', 'services']
['financial', 'services', 'financial', 'sector', 'economics', 'of', 'banking']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['financial', 'services', 'financial', 'sector']
['financial', 'services', 'economics', 'of', 'banking']
['financial', 'sector', 'banking', 'financial', 'services']
['beverage', 'industry']
['financial', 'services']
['bank']
['beverage', 'industry']
['other', 'credit', 'granting', 'insurance', 'financial', 'services', 'bank']
['brewing']
['brewing']
['food', 'and', 'tobacco', 'industry', 'Manufacture', 'of', 'beer', 'brewing']
['higher', 'education']
['telecommunication']
['software', 'as', 'a', 'service']
['brewing']
['financial', 'sector', 'financial', 'services']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['financial', 'sector', 'financial', 'services']
['financial', 'services', 'financial', 'sector', 'economics', 'of', 'banking']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['financial', 'sector', 'financial', 'services']
['insurance', 'financial', 'services', 'Siam', 'Commercial', 'Bank', 'financial', 'sector', 'economics', 'of', 'banking']
['financial', 'services', 'financial', 'sector', 'economics', 'of', 'banking']
['brewing']
['financial', 'services', 'economics', 'of', 'banking']
['brewing']
['financial', 'services']
['economics', 'of', 'banking']
['financial', 'sector']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['financial', 'sector']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['financial', 'services']
['hospitality', 'industry']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['financial', 'services']
['information', 'technology', 'digital', 'marketing', 'consulting', 'company']
['mechanical', 'engineering', 'automotive', 'industry']
['infant', 'equipment', 'food', 'industry']
['manufacture', 'of', 'motor', 'vehicles', 'automotive', 'industry']
['real', 'estate', 'development']
['film', 'industry']
['automotive', 'industry', 'motor', 'scooter']
['automotive', 'industry']
['automotive', 'industry']
['online', 'video', 'platform']
['automotive', 'industry']
['clothing', 'industry', 'fashion']
['information', 'technology', 'pharmaceutical', 'industry', 'plastics', 'industry', 'paint', 'industry', 'chemical', 'industry']
['research', 'and', 'development']
['video', 'game', 'industry']
['film', 'industry']
['retail']
['television']
['automotive', 'industry']
['video', 'game', 'industry']
['media', 'industry']
['automotive', 'industry', 'vehicle', 'construction']
['video', 'game', 'industry']
['automotive', 'industry']
['arms', 'industry']
['biotechnology']
['entertainment']
['automotive', 'industry']
['automotive', 'industry']
['watchmaking', 'defense', 'industry']
['retail', 'clothing', 'industry']
['information', 'technology']
['video', 'game', 'industry']
['Internet', 'marketing']
['carsharing']
['retail', 'perfumery', 'clothing', 'industry']
['light', 'industry']
['toy', 'industry']
['automotive', 'industry']
['fashion']
['satellite', 'television']
['automotive', 'industry']
['manufacturing', 'furniture']
['automotive', 'industry']
['automotive', 'industry']
['cinematography']
['clothing', 'industry']
['manufacture', 'of', 'motor', 'vehicles', 'trailers', 'and', 'semi-trailers', 'automotive', 'industry']
['logistics']
['automotive', 'industry']
['automotive', 'industry']
['automotive', 'industry']
['automotive', 'industry']
['television', 'electronics', 'industry']
['brewing']
['brewing']
['brewing']
['brewing']
['financial', 'services']
['financial', 'services']
['financial', 'services']
['bank']
['financial', 'sector', 'economics', 'of', 'banking']
['bank']
['automotive', 'industry']
['automotive', 'industry']
['mechanical', 'engineering', 'automotive', 'industry']
['automotive', 'industry']
['automotive', 'industry']
['video', 'game', 'industry', 'electronics']
['automotive', 'industry']
['automotive', 'industry']
['retail']
['jewelry', 'industry', 'horology']
['manufacturing']
['video', 'game', 'industry']
['educational', 'technology']
['cosmetics', 'industry']
['arms', 'industry']
['automotive', 'industry']
['networking', 'hardware']
['telecommunications', 'mobile', 'phone', 'industry']
['fashion']
['brewing']
['financial', 'sector']
['bank']
['brewing']
['brewing']
['health', 'care']
['financial', 'sector', 'financial', 'services']
['financial', 'services', 'financial', 'sector', 'economics', 'of', 'banking']
['brewing']
['bank']
['bank', 'finance']
['brewing']
['retail']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['finance']
['brewery', 'malt']
['brewing']
['terrestrial', 'television']
['food', 'and', 'tobacco', 'industry']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['economics', 'of', 'banking']
['insurance']
['retail']
['e-commerce']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['financial', 'services']
['financial', 'services']
['food', 'industry']
['beverage', 'industry']
['prison']
['brewing']
['real', 'estate', 'economics']
['fashion']
['brewing']
['automotive', 'industry']
['artificial', 'intelligence']
['financial', 'services']
['financial', 'sector', 'financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding', 'economics', 'of', 'banking']
['bank']
['brewing']
['brewing']
['textile', 'industry']
['video', 'game', 'industry', 'video', 'game', 'development']
['automotive', 'industry']
['semiconductor', 'electronics']
['financial', 'sector']
['brewing']
['brewing']
['brewing']
['brewing']
['brewing']
['food', 'delivery', 'service']
['publishing']
['retail', 'electric', 'vehicle', 'charging', 'network', 'car', 'washing']
['solar', 'industry']
['battery', 'industry']
['electric', 'vehicle', 'charging', 'station']
['financial', 'services', 'financial', 'sector', 'economics', 'of', 'banking']
['economics', 'of', 'banking']
['finance']
['financial', 'services']
['financial', 'services']
['economics', 'of', 'banking']
['brewing']
['brewing']
['automotive', 'industry']
['automotive', 'industry']
['financial', 'sector']
['financial', 'services']
['beverage', 'industry']
['financial', 'sector', 'financial', 'services', 'economics', 'of', 'banking']
['information', 'technology', 'private', 'equity', 'software', 'industry', 'insurance', 'industry', 'tech', 'industry', 'economics', 'of', 'banking']
['financial', 'services']
['financial', 'services']
['financial', 'sector']
['financial', 'sector']
['insurance', 'industry', 'economics', 'of', 'banking']
['retail']
['retail']
['real', 'estate', 'economics']
['real', 'estate', 'investment', 'trust']
['retail']
['retail', 'food', 'retail', 'sector']
['retail']
['retail']
['motel', 'chain', 'motel', 'hotel', 'industry']
['real', 'estate', 'investment', 'trust']
['retail']
['outlet', 'store']
['online', 'banking']
['logistics', 'sōgō', 'shōsha']
['hospitality', 'industry']
['automotive', 'industry']
['digital', 'distribution']
['brewing']
['brewing']
['tourism', 'hospitality']
['music', 'industry', 'clothing', 'industry', 'audiovisual', 'industry']
['peer-to-peer', 'ridesharing', 'information', 'technology']
['transport', 'taxi', 'service']
['food', 'delivery', 'service', 'information', 'technology', 'peer-to-peer', 'ridesharing']
['transportation', 'industry']
['information', 'technology', 'aggregator', 'taxi', 'service', 'transportation', 'industry']
['telecommunications']
['telecommunications', 'mobile', 'phone', 'industry']
['telecommunications']
['porcelain', 'and', 'ceramic', 'industry']
['other', 'mining', 'and', 'quarrying', 'Manufacture', 'of', 'ceramic', 'household', 'and', 'ornamental', 'articles']
['other', 'mining', 'and', 'quarrying']
['porcelain', 'and', 'ceramic', 'industry']
['telecommunications']
['ceramics', 'industry']
['ceramics', 'industry']
['e-commerce', 'financial', 'services']
['porcelain', 'and', 'ceramic', 'industry']
['music', 'industry', 'phonographic', 'industry']
['retail', 'chain']
['telecommunication', 'mobile', 'network', 'operator']
['telecommunications']
['news', 'media']
['news', 'agency']
['news', 'media']
['journalism']
['news', 'media']
['mass', 'media']
['news', 'media']
['print', 'syndication']
['news', 'media']
['media', 'industry']
['rail', 'freight', 'transport']
['rail', 'transport']
['journalism']
['news', 'media']
['news', 'agency']
['news', 'media']
['financial', 'sector']
['mass', 'media']
['syndication']
['news', 'media']
['public', 'transport']
['passenger', 'rail', 'transport', 'interurban', '(NACE', '49.1)', 'Other', 'accommodation', 'accommodation', 'and', 'food', 'service', 'activities', 'rail', 'transport']
['news', 'media']
['music', 'publishing']
['mass', 'media']
['mass', 'media']
['radio', 'broadcasting']
['filmmaking']
['filmmaking']
['cinematography']
['filmmaking', 'film', 'distribution']
['filmmaking']
['motion', 'picture', 'video', 'and', 'television', 'programme', 'production', 'activities']
['filmmaking']
['rail', 'transport']
['film', 'industry']
['public', 'transport']
['rail', 'transport']
['drinking', 'water']
['water', 'collection', 'treatment', 'and', 'supply']
['mass', 'media']
['news', 'agency']
['music', 'industry', 'phonographic', 'industry']
['television', 'radio', 'broadcasting', 'news', 'media', 'publishing']
['Motion', 'Picture', 'Production', 'and', 'Services']
['mass', 'media']
['filmmaking']
['cinematography']
['news', 'media', 'website', 'insurance']
['filmmaking']
['film', 'industry']
['filmmaking']
['Media']
['cinematography']
['film', 'industry']
['film', 'industry']
['film', 'industry']
['audiovisual', 'production']
['cinematography']
['media', 'industry', 'filmmaking', 'show', 'business', 'film', 'distribution', 'television', 'production']
['film', 'industry']
['media', 'industry', 'broadcasting']
['mass', 'media', 'magazine', 'publishing']
['entertainment', 'industry']
['film', 'industry', 'tourism', 'industry', 'amusement', 'park', 'entertainment', 'industry', 'media', 'industry', 'leisure', 'industries', 'animation']
['live', 'streaming', 'video', 'on', 'demand']
['cinematography', 'activités', 'des', 'sociétés', 'holding']
['film', 'industry']
['hotel']
['retail']
['motel']
['rail', 'transport']
['filmmaking']
['film', 'preservation']
['streaming', 'media']
['filmmaking', 'film', 'distribution']
['streaming', 'media', 'DVD-by-mail', 'filmmaking', 'film', 'distribution', 'television', 'production']
['retail', 'clothing', 'industry', 'textile', 'industry']
['retail']
['film', 'industry']
['filmmaking']
['television']
['film', 'industry']
['cinematography']
['filmmaking', 'computer-generated', 'imagery']
['filmmaking']
['film', 'industry']
['pornography', 'industry']
['animation']
['computer', 'graphics']
['financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding', 'financial', 'services']
['Cinema']
['film', 'distribution', 'film', 'industry']
['cinematography']
['film', 'industry']
['filmmaking', 'show', 'business']
['financial', 'services']
['film', 'industry']
['filmmaking']
['rail', 'transport']
['transportation', 'industry']
['retail']
['film', 'industry']
['bank']
['film', 'industry']
['private', 'bank']
['financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding', 'financial', 'services']
['private', 'banking', 'financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding']
['financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding']
['bank']
['financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding', 'financial', 'services']
['film', 'industry']
['pornography', 'industry']
['film', 'industry']
['cinematography']
['cinematography']
['film', 'industry']
['film', 'industry']
['film', 'industry']
['entertainment']
['cinematography']
['filmmaking']
['financial', 'sector']
['cinematography', 'filmmaking']
['cinematography']
['film', 'industry']
['television', 'film', 'industry']
['transport']
['e-commerce']
['financial', 'service', 'activities', 'except', 'insurance', 'and', 'pension', 'funding']
['pornography', 'industry']
['media', 'industry', 'filmmaking', 'entertainment']
['rail', 'freight', 'transport']
['regional', 'rail']
['Internet', 'industry', 'tourism']
['film', 'industry']
['filmmaking']
['entertainment']
['conglomerate']
['leisure', 'industry', 'bicycle', 'industry', 'clothing', 'industry']
['bicycle', 'industry', 'automotive', 'industry']
['shipyard']
['building', 'of', 'pleasure', 'and', 'sporting', 'boats']
['building', 'of', 'pleasure', 'and', 'sporting', 'boats']
['building', 'of', 'pleasure', 'and', 'sporting', 'boats']
['clothing', 'industry', 'textile', 'industry', 'retail']
['drugstore']
['retail']
['retail', 'chain', 'retail', 'wholesale', 'big-box', 'store']
['retail']
['retail']
['retail']
['retail']
['retail']
['retail']
['textile', 'industry']
['fashion']
['retail']
['automotive', 'industry']
['textile', 'and', 'clothing', 'industry', 'clothing', 'industry']
['retail']
['hairdresser']
['retail', 'textile', 'and', 'clothing', 'industry', 'textile', 'industry']
['drugstore', 'retail']
['mechanical', 'engineering']
['retail']
['cosmetics', 'industry', 'retail']
['trade']
['fashion']
['retail']
['retail', 'textile', 'industry']
['light', 'industry', 'retail']
['automotive', 'industry']
['mass-market', 'retailing']
['retail']
['retail']
['retail']
['retail']
['retail']
['tobacco', 'industry']
['clothing', 'industry']
['retail', 'discount', 'store']
['retail']
['retail']
['aircraft', 'industry', 'automotive', 'industry']
['coffee', 'bar']
['retail']
['aerospace']
['gastronomy']
['retail']
['retail', 'clothing', 'industry']
['retail']
['Wholesale']
['retail']
['automotive', 'industry']
['toy']
['retail']
['fashion']
['printing', 'industry']
['retail']
['retail']
['retail']
['mass-market', 'retailing']
['discount', 'store']
['outdoor', 'recreation', 'shooting', 'fishing', 'hunting', 'camping']
['automotive', 'industry']
['retail']
['real', 'estate', 'economics', 'estate', 'agent']
['retail']
['retail']
['retail']
['retail']
['retail']
['retail']
['department', 'store']
['retail']
['retail']
['retail']
['fashion']
['equipment', 'rental']
['retail']
['bookselling']
['retail', 'duty-free', 'shop']
['retail', 'game', 'industry']
['product', 'distribution']
['retail']
['retail']
['retail', 'chain']
['retail']
['retail']
['clothing', 'industry']
['consumer', 'electronics']
['retail']
['automotive', 'industry']
['retail']
['mass-market', 'retailing']
['consumer', 'electronics', 'retail']
['food', 'industry']
['Coffee', 'and', 'Tea', 'Manufacturing']
['photo', 'industry', 'chemical', 'industry', 'Precision', 'engineering', 'and', 'optical', 'industry']
['computer', 'hardware', 'information', 'technology', 'International', 'Standard', 'Industrial', 'Classification']
['Precision', 'engineering', 'and', 'optical', 'industry', 'photo', 'industry']
['energy', 'supply']
['electronics', 'industry', 'toy', 'industry', 'leisure', 'industry']
['electric', 'power', 'industry']
['hydroelectricity']
['electronics', 'photography']
['digital', 'cinematography']
['photo', 'industry']
['energy', 'supply']
['industrial', 'sector']
['electrical', 'industry', 'video', 'game', 'industry', 'electronics', 'industry']
['film', 'industry']
['electronics', 'electrical', 'industry']
['electronics', 'home', 'appliance', 'video', 'game', 'industry', 'semiconductor', 'industry']
['film', 'equipment', 'industry']
['photography']
['petroleum', 'industry']
['marketing', 'public', 'relations', 'advertising']
['petroleum', 'industry']
['automotive', 'industry']
['manufacture', 'of', 'refined', 'petroleum', 'products', 'petroleum', 'industry']
['petroleum', 'industry']
['petroleum', 'industry']
['petroleum', 'industry']
['petroleum', 'industry', 'activities', 'of', 'head', 'offices', 'energy', 'industry', 'extraction', 'of', 'crude', 'petroleum', 'and', 'natural', 'gas']
['petroleum', 'industry']
['petroleum', 'industry']
['petroleum', 'industry']
['public', 'relations']
['petroleum', 'industry']
['business', 'and', 'other', 'management', 'consulting']

In [ ]:
def find_naics_code(sectors):
    row = set([sectors])

TypeError: unhashable type: 'list'